/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Barnahus_Baked-v1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Cube026" position={[-0.41, 1.2, -0.23]} scale={2.6}>
        <mesh name="Cube195" geometry={nodes.Cube195.geometry} material={materials.Wall} />
        <mesh name="Cube195_1" geometry={nodes.Cube195_1.geometry} material={materials['Mosaic 01']} />
        <mesh name="Cube195_2" geometry={nodes.Cube195_2.geometry} material={materials.Schild} />
        <mesh name="Cube195_3" geometry={nodes.Cube195_3.geometry} material={materials['Gray black pastic']} />
        <mesh name="Cube195_4" geometry={nodes.Cube195_4.geometry} material={materials['Gray gray pastic.001']} />
        <mesh name="Cube195_5" geometry={nodes.Cube195_5.geometry} material={materials['Metal.001']} />
        <mesh name="Cube195_6" geometry={nodes.Cube195_6.geometry} material={materials['Material.004']} />
        <mesh name="Cube195_7" geometry={nodes.Cube195_7.geometry} material={materials['Kunststof-Isolator-schwarz']} />
        <mesh name="Cube195_8" geometry={nodes.Cube195_8.geometry} material={materials['Kunststof-Isolator-rot']} />
        <mesh name="Cube195_9" geometry={nodes.Cube195_9.geometry} material={materials['Gray white plastic']} />
        <mesh name="Cube195_10" geometry={nodes.Cube195_10.geometry} material={materials.pcb} />
        <mesh name="Cube195_11" geometry={nodes.Cube195_11.geometry} material={materials['LED.C.V']} />
        <mesh name="Cube195_12" geometry={nodes.Cube195_12.geometry} material={materials['LED.C.V']} />
        <mesh name="Cube195_13" geometry={nodes.Cube195_13.geometry} material={materials['Kunststof-volt switsch']} />
        <mesh name="Cube195_14" geometry={nodes.Cube195_14.geometry} material={materials['Mat.003']} />
        <mesh name="Cube195_15" geometry={nodes.Cube195_15.geometry} material={materials['Gray white plastic']} />
        <mesh name="Cube195_16" geometry={nodes.Cube195_16.geometry} material={materials['Hinter-scheibe_Rand']} />
        <mesh name="Cube195_17" geometry={nodes.Cube195_17.geometry} material={materials['Hintergrund-scheibe']} />
        <mesh name="Cube195_18" geometry={nodes.Cube195_18.geometry} material={materials['Gray white plastic.Dunkel']} />
        <mesh name="Cube195_19" geometry={nodes.Cube195_19.geometry} material={materials['Nikon.001']} />
        <mesh name="Cube195_20" geometry={nodes.Cube195_20.geometry} material={materials['Lack_black.Mat']} />
        <mesh name="Cube195_21" geometry={nodes.Cube195_21.geometry} material={materials.Metal_black_schraube} />
        <mesh name="Cube195_22" geometry={nodes.Cube195_22.geometry} material={materials['Gummy.001']} />
        <mesh name="Cube195_23" geometry={nodes.Cube195_23.geometry} material={materials['Plastik-blau']} />
        <mesh name="Cube195_24" geometry={nodes.Cube195_24.geometry} material={materials['Plastik.rot']} />
        <mesh name="Cube195_25" geometry={nodes.Cube195_25.geometry} material={materials['Plastik.schwarz']} />
        <mesh name="Cube195_26" geometry={nodes.Cube195_26.geometry} material={materials['Plastik.gelb']} />
        <mesh name="Cube195_27" geometry={nodes.Cube195_27.geometry} material={materials['Material.005']} />
        <mesh name="Cube195_28" geometry={nodes.Cube195_28.geometry} material={materials['Nikon.001']} />
        <mesh name="Cube195_29" geometry={nodes.Cube195_29.geometry} material={materials.Glas} />
        <mesh name="Cube195_30" geometry={nodes.Cube195_30.geometry} material={materials.Gummy} />
        <mesh name="Cube195_31" geometry={nodes.Cube195_31.geometry} material={materials['Iron Touched']} />
        <mesh name="Cube195_32" geometry={nodes.Cube195_32.geometry} material={materials.hole} />
        <mesh name="Cube195_33" geometry={nodes.Cube195_33.geometry} material={materials['plastic touched']} />
        <mesh name="Cube195_34" geometry={nodes.Cube195_34.geometry} material={materials.Box} />
        <mesh name="Cube195_35" geometry={nodes.Cube195_35.geometry} material={materials['Alluminium Notebook body']} />
        <mesh name="Cube195_36" geometry={nodes.Cube195_36.geometry} material={materials['02 - Default']} />
        <mesh name="Cube195_37" geometry={nodes.Cube195_37.geometry} material={materials['Metal NEW']} />
        <mesh name="Cube195_38" geometry={nodes.Cube195_38.geometry} material={materials['Bio cup red']} />
        <mesh name="Cube195_39" geometry={nodes.Cube195_39.geometry} material={materials['Bio cup yellow']} />
        <mesh name="Cube195_40" geometry={nodes.Cube195_40.geometry} material={materials['Metal NEW']} />
        <mesh name="Cube195_41" geometry={nodes.Cube195_41.geometry} material={materials['Material #14']} />
        <mesh name="Cube195_42" geometry={nodes.Cube195_42.geometry} material={materials['Blue Suede Leather']} />
        <mesh name="Cube195_43" geometry={nodes.Cube195_43.geometry} material={materials.hole} />
        <mesh name="Cube195_44" geometry={nodes.Cube195_44.geometry} material={materials.Spring} />
        <mesh name="Cube195_45" geometry={nodes.Cube195_45.geometry} material={materials['paint RAL 7035']} />
        <mesh name="Cube195_46" geometry={nodes.Cube195_46.geometry} material={materials['paint black']} />
        <mesh name="Cube195_47" geometry={nodes.Cube195_47.geometry} material={materials['plastic black']} />
        <mesh name="Cube195_48" geometry={nodes.Cube195_48.geometry} material={materials.Material} />
        <mesh name="Cube195_49" geometry={nodes.Cube195_49.geometry} material={materials['tirqua paper']} />
        <mesh name="Cube195_50" geometry={nodes.Cube195_50.geometry} material={materials.Material13} />
        <mesh name="Cube195_51" geometry={nodes.Cube195_51.geometry} material={materials['[Color_008]1']} />
        <mesh name="Cube195_52" geometry={nodes.Cube195_52.geometry} material={materials.skp_front_default} />
        <mesh name="Cube195_53" geometry={nodes.Cube195_53.geometry} material={materials.skp_front_default} />
        <mesh name="Cube195_54" geometry={nodes.Cube195_54.geometry} material={materials['[Color_002]4']} />
        <mesh name="Cube195_55" geometry={nodes.Cube195_55.geometry} material={materials['[Color_007]4']} />
        <mesh name="Cube195_56" geometry={nodes.Cube195_56.geometry} material={materials.skp_front_default} />
        <mesh name="Cube195_57" geometry={nodes.Cube195_57.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh name="Cube195_58" geometry={nodes.Cube195_58.geometry} material={materials.Color_001} />
        <mesh name="Cube195_59" geometry={nodes.Cube195_59.geometry} material={materials['[Color_003]1']} />
        <mesh name="Cube195_60" geometry={nodes.Cube195_60.geometry} material={materials['[Color_006]1']} />
        <mesh name="Cube195_61" geometry={nodes.Cube195_61.geometry} material={materials['0137_Black']} />
        <mesh name="Cube195_62" geometry={nodes.Cube195_62.geometry} material={materials['logitech-logo']} />
        <mesh name="Cube195_63" geometry={nodes.Cube195_63.geometry} material={materials['0136_Charcoal']} />
        <mesh name="Cube195_64" geometry={nodes.Cube195_64.geometry} material={materials['steel.001']} />
        <mesh name="Cube195_65" geometry={nodes.Cube195_65.geometry} material={materials.Spring} />
        <mesh name="Cube195_66" geometry={nodes.Cube195_66.geometry} material={materials['Black Plastic']} />
        <mesh name="Cube195_67" geometry={nodes.Cube195_67.geometry} material={materials.FABRIC} />
        <mesh name="Cube195_68" geometry={nodes.Cube195_68.geometry} material={materials['RUBBER BUSH']} />
        <mesh name="Cube195_69" geometry={nodes.Cube195_69.geometry} material={materials.emmision} />
      </group>
    </group>
  )
}

useGLTF.preload('/Barnahus_Baked-v1.glb')
